### ISSUE TITLE
cucumberTestCompile not found

### ISSUE THREAD

**Issue by michaeloa** [double16/gradle-cucumber-jvm-plugin#7]
When I try to use this (Kotlin DSL) I get 

Configuration with name 'cucumberTestCompile' not found.

**Comment by double16** [comment]
Which version of the plugin? Which version of Gradle?

**Comment by kmaterka** [comment]
This might be fixed in 0.18 (regression in 0.17)

**Comment by michaeloa** [comment]
Tried it with several versions of gradle, but the latest test was with 6.0.1. And it's with the latest version of the plugin (0.18).

I am using the Kotlin DSL, though I think that shouldn't matter.

**Comment by kmaterka** [comment]
It might be related to Kotlin. How did you configure source set? According to Readme, for Kotlin you must use this syntax:
```Kotlin
cucumber {
    suite("cucumberTest")
}
```

**Comment by michaeloa** [comment]
Yep. the build.gradle.kts (edited for most of the irrelevant chaff):

```
plugins {
    java
    maven
    id("com.patdouble.cucumber-jvm") version "0.18"
}

repositories {
  // Link to maven
}

dependencies {
  // Project dependencies
  add("cucumberTestCompile", "info.cukes:cucumber-java:1.2.5")
  ...etc
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Test> {
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

cucumber {
    suite("cucumberTest")
}

```

**Comment by kmaterka** [comment]
Have you tried "cucumberTestImplementation"? The "compile" scope is deprecated.
You can list all scopes using `gradle dependencies` - firstly comment out the line `add("cucumberTestCompile", "info.cukes:cucumber-java:1.2.5")`.

I will test Kotlin setup tomorrow, now I'm just guessing.

BTW: There is version `0.19` released, with another important fix. Unfortunately Readme is not updated yet.
BTW2: cucumber-java:1.2.5 is very old, I suggest upgrade to latest version. While fixing compatibility issues with Gradle 6 we also upgraded cucumber, it might work with old versions, but it was not tested.

**Comment by kmaterka** [comment]
In my project I'm using something like this:
```groovy
addCucumberSuite('cucumber')
configurations {
    cucumberCompileOnly.extendsFrom testCompileOnly, compileOnly
    cucumberImplementation.extendsFrom testImplementation
    cucumberRuntime.extendsFrom testRuntime
    cucumberAnnotationProcessor.extendsFrom testAnnotationProcessor
}
```
I'm not using Kotlin, just Groovy.

**Comment by kmaterka** [comment]
1. Move plugin configuration before dependencies. If not, then Gradle will not know about "cucumberTest" suite when dependency section is configured.
2. Use `cucumberTestImplementation`

Working example:
```kotlin
plugins {
    java
    id("com.patdouble.cucumber-jvm") version "0.19"
}
repositories {
    mavenCentral()
}
cucumber {
    suite("cucumberTest")
}
dependencies {
    add("cucumberTestImplementation", "io.cucumber:cucumber-java:4.8.0")
}
```
I will create a PR to update documentation.

**Comment by michaeloa** [comment]
Yes! That worked - hadn't thought to try that. Breaks our conventions for build files, but at least it works.

The old cucumber version is because I grabbed the script from a legacy application (forget why, but it struggles to work with the newer versions), so - for now at least - we're stuck with that.

Thanks again and Merry Christmas.

**Comment by kmaterka** [comment]
Great it helped! Can you close this issue? I'm not the owner of this repository, I can't do that.
