### ISSUE TITLE
[0.18] NoClassDefFoundError: groovyx/gpars/GParsPool

### ISSUE THREAD

**Issue by kmaterka** [double16/gradle-cucumber-jvm-plugin#8]
When running cucumber task I get `NoClassDefFoundError: groovyx/gpars/GParsPool`. Something is wrong with shadow jar, it does not include all required dependencies.

Instead of fixing shadow jar it is better to use dependencies. In new Gradle versions dependency leak is less of a problem, especially with new plugin DSL.

I will provide pull request.

**Comment by kmaterka** [comment]
Pull Request: #9

**Comment by double16** [comment]
0.19 released
